CONFIGS = [
    {
        "seed": 42,
        "min_w": 5,
        "min_h": 5,
        "max_w": 10,
        "max_h": 10,
        "num_stocks": 5,
        "max_product_type": 3,
        "max_product_per_type": 5,
    },
    {
        "seed": 42,
        "min_w": 10,
        "min_h": 10,
        "max_w": 20,
        "max_h": 20,
        "num_stocks": 10,
        "max_product_type": 5,
        "max_product_per_type": 10,
    },
    {
        "seed": 42,
        "min_w": 20,
        "min_h": 20,
        "max_w": 50,
        "max_h": 50,
        "num_stocks": 100,
        "max_product_type": 10,
        "max_product_per_type": 15,
    },
    {
        "seed": 42,
        "min_w": 50,
        "min_h": 50,
        "max_w": 100,
        "max_h": 100,
        "num_stocks": 100,
        "max_product_type": 25,
        "max_product_per_type": 20,
    },
    {
        "seed": 47,
        "min_w": 50,
        "min_h": 50,
        "max_w": 100,
        "max_h": 100,
        "num_stocks": 100,
        "max_product_type": 25,
        "max_product_per_type": 20,
    },
    {
        "seed": 49,
        "min_w": 50,
        "min_h": 50,
        "max_w": 100,
        "max_h": 100,
        "num_stocks": 100,
        "max_product_type": 25,
        "max_product_per_type": 20,
    },
    {
        "seed": 42,
        "min_w": 20,
        "min_h": 20,
        "max_w": 100,
        "max_h": 100,
        "num_stocks": 100,
        "max_product_type": 25,
        "max_product_per_type": 20,
    },
    {
        "seed": 42,
        "min_w": 50,
        "min_h": 50,
        "max_w": 100,
        "max_h": 100,
        "num_stocks": 100,
        "max_product_type": 40,
        "max_product_per_type": 10,
    },
    {
        "seed": 42,
        "min_w": 50,
        "min_h": 50,
        "max_w": 100,
        "max_h": 100,
        "num_stocks": 150,
        "max_product_type": 25,
        "max_product_per_type": 20,
    },
    {
        "seed": 42,
        "min_w": 20,
        "min_h": 20,
        "max_w": 100,
        "max_h": 100,
        "num_stocks": 200,
        "max_product_type": 40,
        "max_product_per_type": 25,
    },
]
